# User config
author: "Bon To Code"
tagline: "ğŸPine CodeğŸ"
description: "ğŸPine CodeğŸ"
keywords: "Pineapple, Pineapple Pizza, Pineapple House"
email: "watchbon@kakao.com"

linkedin: "https://www.linkedin.com/"
twitter: "https://twitter.com/"
github: "https://github.com/99kb/"

# Site config
url: "https://99kb.github.io"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
